'use client'
import { useEffect,useMemo,useRef,useState } from 'react'
import SiteHeader from '@/components/SiteHeader'
import CapturaEmail from '@/components/CapturaEmail'
import { SEOAutonomos } from '@/components/SEOContent/SEOContent'
import RegimenQuestions from '@/components/RegimenQuestions'
import { MONTOS,FALLBACK_VENC,FALLBACK_ALERTAS,addFecha,diffDias,fmtLarga,fmtCorta,money,type VencimientoUI,type AlertaUI } from '@/lib/data'

const TIPO='aut'
const V={tealDark:'#0d5c78',teal:'#1a7fa8',tealMid:'#2490bc',tealLight:'#e8f6fb',tealRing:'#a8ddf0',gold:'#f5a623',goldLight:'#fff8ec',goldRing:'#fde4a0',red:'#e53535',redBg:'#fff1f1',redRing:'#ffc8c8',amber:'#d97706',amberBg:'#fffbeb',amberRing:'#fde68a',bg:'#f4f7f9',surface:'#fff',border:'#e2e8ed',ink:'#0f2733',ink2:'#3d5a6b',ink3:'#7a9aaa'}
function cardCfg(d:number){return d===0?{bg:`linear-gradient(150deg,#fff 65%,${V.redBg})`,border:V.redRing,pillBg:V.redBg,pillColor:V.red,txt:'🔴 Vence HOY',diasColor:V.red,diasTxt:'¡HOY!'}:d===1?{bg:`linear-gradient(150deg,#fff 65%,${V.goldLight})`,border:V.goldRing,pillBg:V.goldLight,pillColor:V.amber,txt:'🟡 Mañana',diasColor:V.amber,diasTxt:'Mañana'}:{bg:`linear-gradient(150deg,#fff 65%,${V.tealLight})`,border:V.tealRing,pillBg:V.tealLight,pillColor:V.tealDark,txt:`🟢 En ${d} días`,diasColor:V.teal,diasTxt:`En ${d} días`}}

export default function AutonomosPage(){
 const[venc,setVenc]=useState<VencimientoUI[]>([]),[alertas,setAlertas]=useState<AlertaUI[]>([]),[catIdx,setCatIdx]=useState(''),[aiQuery,setAiQuery]=useState(''),[aiResp,setAiResp]=useState(''),[aiLoading,setAiLoading]=useState(false),[mounted,setMounted]=useState(false)
 const capturaRef=useRef<HTMLInputElement>(null)
 useEffect(()=>setMounted(true),[])
 useEffect(()=>{fetch(`/api/vencimientos?tipo=${TIPO}`).then(r=>r.json()).then(d=>setVenc((d.vencimientos||[]).map(addFecha))).catch(()=>setVenc(FALLBACK_VENC[TIPO].map(addFecha)));fetch(`/api/alerts?tipo=${TIPO}`).then(r=>r.json()).then(d=>setAlertas(d.alerts||FALLBACK_ALERTAS[TIPO])).catch(()=>setAlertas(FALLBACK_ALERTAS[TIPO]))},[])
 async function askAI(q?:string){const query=q||aiQuery;if(!query.trim())return;if(q)setAiQuery(q);setAiLoading(true);setAiResp('');try{const r=await fetch('/api/fiscal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const d=await r.json();setAiResp(d.response||'Sin respuesta.')}catch{setAiResp('Error de conexión.')}finally{setAiLoading(false)}}
 const vencOrd=useMemo(()=>[...venc].filter(v=>diffDias(v.fecha)>=0).sort((a,b)=>diffDias(a.fecha)-diffDias(b.fecha)),[venc]),cards=useMemo(()=>vencOrd.slice(0,3),[vencOrd]),proximos=useMemo(()=>vencOrd.filter(v=>diffDias(v.fecha)<=10).slice(0,8),[vencOrd])
 const idx=catIdx===''?-1:Number(catIdx),aporte=idx>=0?MONTOS[TIPO].imp[idx]:0
 const fechaHoy=mounted?new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date()):''
 return <><SiteHeader currentPath="/autonomos" onAlertasClick={()=>{capturaRef.current?.scrollIntoView({behavior:'smooth'});setTimeout(()=>capturaRef.current?.focus(),600)}}/><div className="ff-page-content">
  <div className="ff-hero" style={{background:`linear-gradient(135deg,${V.tealDark},${V.teal})`,position:'relative',overflow:'hidden'}}><div style={{maxWidth:640,margin:'0 auto',position:'relative',zIndex:1}}><div style={{display:'inline-flex',gap:6,background:'rgba(255,255,255,.12)',border:'1px solid rgba(255,255,255,.2)',borderRadius:20,padding:'5px 14px',marginBottom:16,fontSize:12,fontWeight:700,color:'white'}}>⚡ Para trabajadores autónomos de Argentina</div><h1>Gestioná tus aportes<br/>como autónomo sin errores</h1><p>Controlá tus aportes previsionales y revisá las obligaciones de IVA y Ganancias que puedan corresponderte.</p><a href="https://www.arca.gob.ar/autonomos/" target="_blank" rel="noopener noreferrer" className="ff-hero-btn">Ver Autónomos en ARCA →</a><div style={{marginTop:10,fontSize:11,color:'rgba(255,255,255,.6)',fontWeight:600}}>Información simple · Fuentes oficiales · Recordatorios gratis</div></div></div>
  <div style={{background:V.surface,borderBottom:`1px solid ${V.border}`}}><div style={{maxWidth:860,margin:'0 auto',padding:'20px 16px'}}><div style={{textAlign:'center',marginBottom:14}}><div style={{fontSize:13,fontWeight:800,color:V.red,marginBottom:4}}>⚠️ Evitá errores ante ARCA</div><div style={{fontSize:16,fontWeight:900,color:V.ink}}>Puntos que conviene revisar</div></div><div className="ff-dolor-grid">{['Pagar una categoría que no corresponde a tu actividad','Confundir Autónomos con IVA o Ganancias','Olvidar el aporte previsional mensual','No revisar la recategorización anual de mayo'].map(txt=><div key={txt} style={{display:'flex',gap:8,background:V.redBg,border:`1px solid ${V.redRing}`,borderRadius:10,padding:'10px 12px'}}><span>❌</span><span style={{fontSize:12,fontWeight:700,color:'#7a2020',lineHeight:1.4}}>{txt}</span></div>)}</div></div></div>
  <main className="ff-main"><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20}}><div style={{fontSize:13,color:V.ink3,fontWeight:600}}>Hoy es <strong style={{color:V.ink2}}>{fechaHoy}</strong></div><div style={{background:V.tealLight,border:`1.5px solid ${V.tealRing}`,borderRadius:20,padding:'4px 12px',fontSize:12,fontWeight:800,color:V.tealDark}}>⚡ Autónomo</div></div>
   <div style={{fontSize:11,fontWeight:800,letterSpacing:'1.5px',textTransform:'uppercase',color:V.ink3,marginBottom:12}}>📅 Próximos vencimientos</div><div className="ff-cards-grid">{cards.length===0?<div style={{padding:'20px 0',color:V.ink3,fontSize:13,fontWeight:600}}>No hay una fecha exacta próxima disponible para mostrar acá. Consultá el calendario fiscal validado.</div>:cards.map(v=>{const d=diffDias(v.fecha),c=cardCfg(d);return <div key={v.id} style={{background:c.bg,border:`1.5px solid ${c.border}`,borderRadius:16,padding:18,display:'flex',flexDirection:'column',gap:12}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:20}}>⚡</span><span style={{background:c.pillBg,color:c.pillColor,borderRadius:20,padding:'4px 10px',fontSize:11,fontWeight:800}}>{c.txt}</span></div><div><div style={{fontSize:15,fontWeight:900,color:V.ink}}>{v.nombre}</div><div style={{fontSize:12,color:V.ink3,fontWeight:600,marginTop:3}}>{v.detalle}</div></div><div style={{display:'flex',justifyContent:'space-between',borderTop:`1px solid ${V.border}`,paddingTop:10}}><span style={{fontSize:13,fontWeight:700,color:V.ink2}}>{fmtLarga(v.fecha)}</span><strong style={{fontSize:13,color:c.diasColor}}>{c.diasTxt}</strong></div><a href="/calendario-fiscal" style={{textAlign:'center',borderRadius:8,padding:10,fontSize:13,fontWeight:800,background:V.bg,color:V.ink2,border:`1.5px solid ${V.border}`,textDecoration:'none'}}>Ver detalles →</a></div>})}</div>
   <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden',marginBottom:20}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800,color:V.ink}}>📋 Lista de vencimientos próximos</div>{proximos.length===0?<div style={{padding:'14px 16px',color:V.ink3,fontSize:13}}>Sin fechas exactas en los próximos 10 días.</div>:proximos.map(v=><div key={v.id} style={{display:'flex',gap:12,padding:'10px 16px',borderBottom:`1px solid ${V.border}`}}><strong style={{fontSize:12,color:V.ink3,minWidth:60}}>{fmtCorta(v.fecha)}</strong><div><div style={{fontSize:13,fontWeight:700,color:V.ink}}>{v.nombre}</div><div style={{fontSize:11,color:V.ink3}}>{v.detalle}</div></div></div>)}</div>
   <div className="ff-two-col"><div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden'}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>⚠️ Alertas importantes</div>{alertas.map(a=><div key={a.id} style={{display:'flex',gap:10,padding:'11px 16px',borderBottom:`1px solid ${V.border}`}}><span>{a.icon}</span><div><div style={{fontSize:12,fontWeight:800,color:V.ink}}>{a.title}</div><div style={{fontSize:11,color:V.ink3,fontWeight:600,lineHeight:1.5}}>{a.description}</div></div></div>)}</div>
    <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden'}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>🧮 Aporte mensual vigente</div><div style={{padding:'14px 16px'}}><div style={{fontSize:11,fontWeight:800,color:V.ink3,marginBottom:5}}>CATEGORÍA DE REVISTA</div><select value={catIdx} onChange={e=>setCatIdx(e.target.value)} style={{width:'100%',border:`1.5px solid ${V.border}`,borderRadius:8,padding:'9px 10px',fontSize:13,background:V.bg,marginBottom:10}}><option value="">— Elegí tu categoría —</option>{MONTOS[TIPO].cats.map((c,i)=><option key={c} value={i}>{c}</option>)}</select><div style={{background:`linear-gradient(135deg,${V.tealDark},${V.tealMid})`,borderRadius:8,padding:16,textAlign:'center',color:'white'}}>{idx>=0?<><div style={{fontSize:28,fontWeight:900}}>{money(aporte)}</div><div style={{fontSize:10,opacity:.7}}>aporte mensual · vigente desde 15/09/2026</div></>:<div style={{fontSize:14,opacity:.5}}>Seleccioná tu categoría</div>}</div><p style={{fontSize:11,color:V.ink3,lineHeight:1.5,marginBottom:0}}>La categoría depende de tu actividad y de las reglas de ARCA. Este importe no incluye IVA, Ganancias ni otros impuestos.</p></div></div></div>
   <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden',margin:'20px 0'}}><div style={{background:'#0a0a1a',color:'white',padding:'9px 14px',fontSize:11,fontWeight:700}}>Asistente IA · Consultas fiscales</div><div style={{padding:'12px 14px'}}><div style={{display:'flex',gap:8}}><input value={aiQuery} onChange={e=>setAiQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askAI()} placeholder="¿Qué categoría de Autónomos me corresponde?" style={{flex:1,border:`1.5px solid ${V.border}`,borderRadius:8,padding:'9px 10px',fontSize:13,background:V.bg}}/><button onClick={()=>askAI()} disabled={aiLoading} style={{background:V.teal,color:'white',border:'none',borderRadius:8,padding:'9px 14px',fontWeight:800}}>{aiLoading?'…':'Consultar →'}</button></div>{(aiLoading||aiResp)&&<div style={{marginTop:10,padding:'10px 12px',background:V.bg,borderRadius:8,borderLeft:`3px solid ${V.teal}`,fontSize:13,color:V.ink2,lineHeight:1.75,whiteSpace:'pre-wrap'}}>{aiLoading?'Consultando ARCA…':aiResp}</div>}</div></div>
   <SEOAutonomos/><RegimenQuestions context="autonomos"/><CapturaEmail ref={capturaRef} tipoDefault="aut"/>
  </main></div></>
}
