import Link from 'next/link'
import SiteHeader from '@/components/SiteHeader'
import StructuredData, { breadcrumbJsonLd, calculatorJsonLd, faqJsonLd } from '@/components/StructuredData'
import { GananciasCalculator } from '@/components/calculadoras/Calculadoras2026'

const faq = [
  { question:'¿Qué dato tengo que ingresar?', answer:'Si trabajás en relación de dependencia, ingresá tu sueldo bruto mensual antes de descuentos. Si trabajás por tu cuenta, ingresá tus ingresos o facturación mensual y, si los conocés, los gastos vinculados con tu actividad.' },
  { question:'¿El resultado es el importe definitivo?', answer:'No. Es una estimación orientativa. El cálculo definitivo puede cambiar por deducciones, retenciones, percepciones, anticipos, otros ingresos y tu situación particular informada ante ARCA.' },
  { question:'¿Cada cuánto se paga Ganancias?', answer:'La determinación para personas humanas es anual. Además, cuando corresponden, ARCA exige anticipos a cuenta del período siguiente. No es un impuesto mensual fijo.' },
  { question:'¿Cuándo vence Ganancias?', answer:'Depende del tipo de contribuyente, período y obligación. ARCA puede modificar o prorrogar fechas; por eso Fácil Fiscal mantiene un calendario separado para los vencimientos.' },
]

export default function Page(){return <>
<StructuredData data={[breadcrumbJsonLd([{name:'Inicio',url:'https://www.facilfiscal.com.ar'},{name:'Ganancias',url:'https://www.facilfiscal.com.ar/impuesto-ganancias'}]),calculatorJsonLd('Calculadora de Ganancias 2026','Estimá Ganancias a partir de cuánto ganás y preguntas simples sobre tu situación.','/impuesto-ganancias'),faqJsonLd(faq)]}/>
<SiteHeader currentPath="/impuesto-ganancias"/><div className="ff-page-content"><GananciasCalculator/>
<main style={{maxWidth:920,margin:'0 auto',padding:'8px 20px 64px',color:'#183744',lineHeight:1.65}}>
<section style={{background:'#f5f3ff',border:'1px solid #ddd6fe',borderRadius:16,padding:22,marginBottom:24}}><h2 style={{marginTop:0}}>Ganancias, explicado fácil</h2><p>Ganancias no se calcula aplicando un porcentaje a todo lo que cobrás. Primero se determina qué ingresos están alcanzados, se descuentan los conceptos admitidos y luego se aplica la escala vigente.</p><p style={{marginBottom:0}}><strong>La calculadora es orientativa.</strong> Otros ingresos, deducciones, retenciones, percepciones o anticipos pueden cambiar el resultado definitivo.</p></section>
<section style={{marginBottom:30}}><h2>¿Me corresponde?</h2><p>Puede alcanzar distintas clases de ingresos, actividades profesionales, empresarias y sociedades. En Mi Panel usamos tu régimen y los datos que declaraste para indicarte si es una obligación que deberías revisar.</p></section>
<section style={{marginBottom:30}}><h2>¿Cómo se calcula?</h2><ol style={{paddingLeft:22}}><li>Se consideran los ingresos alcanzados.</li><li>Se restan gastos y deducciones admitidos.</li><li>Se obtiene la ganancia neta sujeta a impuesto y se aplica la escala vigente.</li><li>Se descuentan pagos computables, como retenciones, percepciones o anticipos.</li></ol><p>La calculadora utiliza parámetros 2026. No usamos escalas históricas como si fueran actuales.</p></section>
<section style={{background:'#ecfdf5',border:'1px solid #a7f3d0',borderRadius:16,padding:22,marginBottom:30}}><h2 style={{marginTop:0}}>🔄 ¿Cada cuánto?</h2><p><strong>Para personas humanas, la determinación es anual.</strong> Además pueden corresponder anticipos durante el ciclo siguiente.</p><p style={{marginBottom:0}}>ARCA informa cinco anticipos para personas humanas y sucesiones indivisas. Son pagos a cuenta: se descuentan al determinar la obligación principal.</p></section>
<section style={{background:'#fff7ed',border:'1px solid #fed7aa',borderRadius:16,padding:22,marginBottom:30}}><h2 style={{marginTop:0}}>📅 Situación vigente en septiembre de 2026</h2><p>Para Ganancias de personas humanas y sucesiones indivisas del período fiscal 2025, ARCA prorrogó la <strong>presentación hasta el 22/09/2026</strong>. El vencimiento del saldo de pago permaneció en el <strong>27/07/2026</strong>.</p><p>Además, mediante la RG 5890/2026, el <strong>primer anticipo de Ganancias 2026</strong> fue trasladado excepcionalmente al <strong>24/09/2026</strong> para todas las terminaciones de CUIT.</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Link href="/calendario-fiscal" style={{background:'#183744',color:'white',padding:'11px 16px',borderRadius:9,fontWeight:800,textDecoration:'none'}}>Ver calendario actualizado →</Link><Link href="/#alertas" style={{background:'#d4a017',color:'#102a36',padding:'11px 16px',borderRadius:9,fontWeight:800,textDecoration:'none'}}>🔔 Recibir recordatorios</Link></div></section>
<section style={{marginBottom:30}}><h2>💳 ¿Cómo se paga?</h2><p>Cuando existe saldo a ingresar, ARCA permite cancelarlo mediante los medios habilitados para la obligación. Entre ellos se encuentra el <strong>VEP</strong>, que puede generarse desde el servicio con clave fiscal “Presentación de DDJJ y Pagos”. Según el caso también pueden existir compensaciones o planes de facilidades.</p><p>Antes de pagar, verificá período, concepto e importe en ARCA: Fácil Fiscal orienta el proceso, pero no reemplaza la cuenta tributaria oficial.</p></section>
<section style={{marginBottom:30}}><h2>Deducciones</h2><p>Las deducciones pueden reducir la base cuando cumplen los requisitos establecidos. Existen deducciones personales y generales, con condiciones y topes según cada concepto.</p></section>
<section style={{marginBottom:30}}><h2>Preguntas frecuentes</h2>{faq.map(i=><details key={i.question} style={{background:'#f8fafc',border:'1px solid #e2e8f0',borderRadius:10,padding:'14px 16px',marginBottom:10}}><summary style={{cursor:'pointer',fontWeight:800}}>{i.question}</summary><p style={{marginBottom:0}}>{i.answer}</p></details>)}</section>
<section style={{borderTop:'1px solid #e2e8f0',paddingTop:22,fontSize:14,color:'#526675'}}><h2 style={{fontSize:20,color:'#183744'}}>Fuentes y actualización</h2><p>Revisado el 14/09/2026 con información oficial de ARCA sobre determinación, escala 2026, anticipos y vencimientos. Las fechas pueden modificarse por nuevas resoluciones.</p><p><a href="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/declaracion-jurada/determinativa/vencimientos.asp" target="_blank" rel="noopener noreferrer">Vencimientos oficiales →</a> · <a href="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/declaracion-jurada/determinativa/anticipos.asp" target="_blank" rel="noopener noreferrer">Anticipos oficiales →</a></p></section>
</main></div></>}
