import Link from 'next/link'
import SiteHeader from '@/components/SiteHeader'
import StructuredData, { breadcrumbJsonLd, calculatorJsonLd, faqJsonLd } from '@/components/StructuredData'
import { GananciasCalculator } from '@/components/calculadoras/Calculadoras2026'
import RegimenQuestions from '@/components/RegimenQuestions'

const faq = [
  { question:'¿Qué dato tengo que ingresar?', answer:'Si trabajás en relación de dependencia, ingresá tu sueldo bruto mensual antes de descuentos. Si trabajás por tu cuenta, ingresá tus ingresos o facturación mensual y, si los conocés, los gastos vinculados con tu actividad.' },
  { question:'¿El resultado es el importe definitivo?', answer:'No. Es una estimación orientativa. El cálculo definitivo puede cambiar por deducciones, retenciones, percepciones, anticipos, otros ingresos y tu situación particular informada ante ARCA.' },
  { question:'¿Cada cuánto se paga Ganancias?', answer:'La determinación para personas humanas es anual. En relación de dependencia el empleador puede practicar retenciones durante el año. Para otras personas humanas, además pueden corresponder anticipos a cuenta del período siguiente.' },
  { question:'¿Qué gastos pueden reducir Ganancias?', answer:'Según tu situación pueden existir deducciones por cargas de familia, alquiler, cuotas médico-asistenciales, casas particulares, gastos educativos, determinados seguros, honorarios médicos y otros conceptos admitidos. Cada uno tiene requisitos y, en muchos casos, topes.' },
  { question:'¿Cuándo vence Ganancias?', answer:'Depende del tipo de contribuyente, período y obligación. ARCA puede modificar o prorrogar fechas; por eso Fácil Fiscal mantiene un calendario separado para los vencimientos.' },
]

export default function Page(){return <>
<StructuredData data={[breadcrumbJsonLd([{name:'Inicio',url:'https://www.facilfiscal.com.ar'},{name:'Ganancias',url:'https://www.facilfiscal.com.ar/impuesto-ganancias'}]),calculatorJsonLd('Calculadora de Ganancias 2026','Estimá Ganancias a partir de cuánto ganás y preguntas simples sobre tu situación.','/impuesto-ganancias'),faqJsonLd(faq)]}/>
<SiteHeader currentPath="/impuesto-ganancias"/><div className="ff-page-content"><GananciasCalculator/>
<main style={{maxWidth:920,margin:'0 auto',padding:'8px 20px 64px',color:'#183744',lineHeight:1.65}}>
<section style={{background:'#f5f3ff',border:'1px solid #ddd6fe',borderRadius:16,padding:22,marginBottom:24}}><h2 style={{marginTop:0}}>Ganancias, explicado fácil</h2><p>Ganancias no se calcula aplicando un porcentaje a todo lo que cobrás. Primero se determina qué ingresos están alcanzados, se descuentan los conceptos admitidos y luego se aplica la escala vigente.</p><p style={{marginBottom:0}}><strong>La calculadora es orientativa.</strong> Otros ingresos, deducciones, retenciones, percepciones o anticipos pueden cambiar el resultado definitivo.</p></section>
<section style={{marginBottom:30}}><h2>¿Me corresponde?</h2><p>Ganancias puede alcanzar situaciones muy distintas. Por eso no conviene usar el mismo cálculo para todos: un empleado en relación de dependencia, una persona que trabaja por cuenta propia y una sociedad tienen mecanismos diferentes.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}><div style={{padding:14,border:'1px solid #e2e8f0',borderRadius:10}}><strong>👤 Empleado</strong><p style={{fontSize:13,marginBottom:0}}>El empleador puede retener Ganancias durante el año y las deducciones informadas pueden modificar el cálculo.</p></div><div style={{padding:14,border:'1px solid #e2e8f0',borderRadius:10}}><strong>🧑‍💼 Independiente</strong><p style={{fontSize:13,marginBottom:0}}>Se consideran ingresos, gastos vinculados, deducciones y pagos computables para determinar el resultado.</p></div><div style={{padding:14,border:'1px solid #e2e8f0',borderRadius:10}}><strong>🏢 Sociedad</strong><p style={{fontSize:13,marginBottom:0}}>La determinación parte del balance impositivo y tiene reglas propias. Esta calculadora simple no liquida sociedades.</p></div></div></section>
<section style={{marginBottom:30}}><h2>¿Cómo se calcula?</h2><ol style={{paddingLeft:22}}><li>Se consideran los ingresos alcanzados.</li><li>Se restan gastos y deducciones admitidos.</li><li>Se obtiene la ganancia neta sujeta a impuesto y se aplica la escala vigente.</li><li>Se descuentan pagos computables, como retenciones, percepciones o anticipos.</li></ol><p>La calculadora utiliza parámetros 2026. No usamos escalas históricas como si fueran actuales.</p></section>
<section style={{background:'#ecfdf5',border:'1px solid #a7f3d0',borderRadius:16,padding:22,marginBottom:30}}><h2 style={{marginTop:0}}>💡 Las deducciones pueden cambiar el resultado</h2><p>No alcanza con saber tu sueldo o facturación. Alquiler de vivienda, cuotas médico-asistenciales, personal de casas particulares, gastos educativos, determinados seguros y gastos médicos son algunos de los conceptos que pueden ser relevantes si cumplen los requisitos de ARCA.</p><p style={{marginBottom:0}}>La calculadora te pregunta primero lo esencial y deja los datos adicionales como opcionales para no convertir el cálculo en un formulario técnico interminable.</p></section>
<section style={{background:'#ecfdf5',border:'1px solid #a7f3d0',borderRadius:16,padding:22,marginBottom:30}}><h2 style={{marginTop:0}}>🔄 ¿Cada cuánto?</h2><p><strong>Para personas humanas, la determinación es anual.</strong> En relación de dependencia puede haber retenciones durante el año y, en otros casos, pueden corresponder anticipos.</p><p style={{marginBottom:0}}>ARCA informa cinco anticipos para personas humanas y sucesiones indivisas. Son pagos a cuenta: se descuentan al determinar la obligación principal.</p></section>
<section style={{background:'#fff7ed',border:'1px solid #fed7aa',borderRadius:16,padding:22,marginBottom:30}}><h2 style={{marginTop:0}}>📅 Vencimientos y períodos: qué revisar</h2><p>Los vencimientos de Ganancias dependen del tipo de contribuyente, período fiscal y terminación de CUIT. Para personas humanas, la declaración jurada anual y el pago del saldo pueden tener fechas distintas. Por ejemplo, para el período fiscal 2025, ARCA informa actualmente presentación hasta el <strong>13/10/2026</strong> y pago del saldo hasta el <strong>27/07/2026</strong>. Si una prórroga modifica el cronograma, verificá la fecha vigente en ARCA antes de actuar.</p><p>Los anticipos de personas humanas son pagos a cuenta —no una cuota mensual— y, según el esquema general, son cinco: agosto, octubre y diciembre del primer año siguiente al período base, y febrero y abril del segundo año. Las fechas concretas pueden ser reprogramadas; consultá el calendario por CUIT.</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Link href="/calendario-fiscal" style={{background:'#183744',color:'white',padding:'11px 16px',borderRadius:9,fontWeight:800,textDecoration:'none'}}>Ver calendario actualizado →</Link><a href="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/declaracion-jurada/determinativa/vencimientos.asp" target="_blank" rel="noopener noreferrer" style={{background:'#d4a017',color:'#102a36',padding:'11px 16px',borderRadius:9,fontWeight:800,textDecoration:'none'}}>Vencimientos oficiales ARCA →</a></div></section>
<section style={{marginBottom:30}}><h2>💳 ¿Cómo y cuándo se paga?</h2><p><strong>Saldo de la declaración anual:</strong> después de presentar la DDJJ, si queda un importe a ingresar, generá un VEP desde “Presentación de Declaraciones Juradas y Pagos” y abonalo desde tu homebanking o una entidad habilitada. ARCA también contempla la Billetera Electrónica y, según el caso, planes de facilidades. Para el saldo de Ganancias de personas humanas, el código informado por ARCA es 11-019-019.</p><p><strong>Anticipos:</strong> son pagos a cuenta del impuesto anual. ARCA informa los importes en “Cuentas Tributarias”; se pagan por VEP u otros medios habilitados, cada uno con su vencimiento. Si estimás que los anticipos superan el impuesto que corresponderá, existe un procedimiento para solicitar su reducción, sujeto a requisitos.</p><ol style={{paddingLeft:22}}><li>Revisá en ARCA el período, el concepto y el importe de la obligación.</li><li>Generá el VEP desde el servicio indicado y elegí el medio electrónico habilitado.</li><li>Completá el pago en tu banco o billetera y guardá el comprobante.</li><li>Volvé a consultar la cuenta tributaria para verificar la imputación.</li></ol><p>Antes de pagar, confirmá el vencimiento vigente según tu situación y CUIT. Fácil Fiscal orienta el proceso, pero no reemplaza la cuenta tributaria oficial.</p><p><a href="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/declaracion-jurada/determinativa/saldos.asp" target="_blank" rel="noopener noreferrer">ARCA: cómo pagar el saldo de la declaración jurada →</a> · <a href="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/declaracion-jurada/determinativa/anticipos.asp" target="_blank" rel="noopener noreferrer">ARCA: anticipos y formas de pago →</a></p></section>
<RegimenQuestions/>
<section style={{marginBottom:30}}><h2>Preguntas frecuentes sobre Ganancias</h2>{faq.map(i=><details key={i.question} style={{background:'#f8fafc',border:'1px solid #e2e8f0',borderRadius:10,padding:'14px 16px',marginBottom:10}}><summary style={{cursor:'pointer',fontWeight:800}}>{i.question}</summary><p style={{marginBottom:0}}>{i.answer}</p></details>)}</section>
<section style={{borderTop:'1px solid #e2e8f0',paddingTop:22,fontSize:14,color:'#526675'}}><h2 style={{fontSize:20,color:'#183744'}}>Fuentes y actualización</h2><p>Revisado el 15/09/2026 con información oficial de ARCA sobre determinación, deducciones, escala 2026, anticipos y vencimientos. Las fechas y parámetros pueden modificarse por nuevas resoluciones.</p><p><a href="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/deducciones/deducciones-generales.asp" target="_blank" rel="noopener noreferrer">Deducciones oficiales →</a> · <a href="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/declaracion-jurada/determinativa/anticipos.asp" target="_blank" rel="noopener noreferrer">Anticipos oficiales →</a></p></section>
</main></div></>}
