'use client'
import { useState, useEffect, useRef, useMemo } from 'react'
import Link from 'next/link'
import SiteHeader from '@/components/SiteHeader'
import CapturaEmail from '@/components/CapturaEmail'
import { SEOMonotributo } from '@/components/SEOContent/SEOContent'
import RegimenQuestions from '@/components/RegimenQuestions'
import { useFiscalData } from '@/components/FiscalDataProvider'
import { FALLBACK_VENC, FALLBACK_ALERTAS, addFecha, diffDias, fmtLarga, fmtCorta, money, type VencimientoUI, type AlertaUI } from '@/lib/data'

const TIPO='mono'
const V={tealDark:'#0d5c78',teal:'#1a7fa8',tealMid:'#2490bc',tealLight:'#e8f6fb',tealRing:'#a8ddf0',gold:'#f5a623',goldDark:'#e8920a',goldLight:'#fff8ec',goldRing:'#fde4a0',red:'#e53535',redBg:'#fff1f1',redRing:'#ffc8c8',amber:'#d97706',amberBg:'#fffbeb',amberRing:'#fde68a',green:'#16a34a',greenBg:'#f0fdf4',greenRing:'#bbf7d0',bg:'#f4f7f9',surface:'#fff',border:'#e2e8ed',ink:'#0f2733',ink2:'#3d5a6b',ink3:'#7a9aaa'}
function cardCfg(d:number){return d===0?{bg:`linear-gradient(150deg,#fff 65%,${V.redBg})`,border:V.redRing,iconBg:V.redBg,pill:{bg:V.redBg,color:V.red,border:V.redRing},txt:'🔴 Vence HOY',diasColor:V.red,diasTxt:'¡HOY!',btnDanger:true}:d===1?{bg:`linear-gradient(150deg,#fff 65%,${V.goldLight})`,border:V.goldRing,iconBg:V.goldLight,pill:{bg:V.goldLight,color:V.amber,border:V.goldRing},txt:'🟡 Mañana',diasColor:V.amber,diasTxt:'Mañana',btnDanger:false}:{bg:`linear-gradient(150deg,#fff 65%,${V.tealLight})`,border:V.tealRing,iconBg:V.tealLight,pill:{bg:V.tealLight,color:V.tealDark,border:V.tealRing},txt:`🟢 En ${d} días`,diasColor:V.teal,diasTxt:`En ${d} días`,btnDanger:false}}
export default function Home(){
 const{categorias}=useFiscalData();const[venc,setVenc]=useState<VencimientoUI[]>([]),[alertas,setAlertas]=useState<AlertaUI[]>([]),[catIdx,setCatIdx]=useState(''),[conOS,setConOS]=useState(true),[actividad,setActividad]=useState<'servicios'|'productos'>('servicios'),[aiQuery,setAiQuery]=useState(''),[aiResp,setAiResp]=useState(''),[aiLoading,setAiLoading]=useState(false),[mounted,setMounted]=useState(false);const capturaRef=useRef<HTMLInputElement>(null)
 useEffect(()=>setMounted(true),[]);useEffect(()=>{fetch(`/api/vencimientos?tipo=${TIPO}`).then(r=>r.json()).then(d=>setVenc((d.vencimientos||[]).map(addFecha))).catch(()=>setVenc(FALLBACK_VENC[TIPO].map(addFecha)));fetch(`/api/alerts?tipo=${TIPO}`).then(r=>r.json()).then(d=>setAlertas(d.alerts||FALLBACK_ALERTAS[TIPO])).catch(()=>setAlertas(FALLBACK_ALERTAS[TIPO]))},[])
 async function askAI(q?:string){const query=q||aiQuery;if(!query.trim())return;if(q)setAiQuery(q);setAiLoading(true);setAiResp('');try{const r=await fetch('/api/fiscal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const d=await r.json();setAiResp(d.response||'Sin respuesta.')}catch{setAiResp('Error de conexión.')}finally{setAiLoading(false)}}
 const vencOrd=useMemo(()=>[...venc].filter(v=>diffDias(v.fecha)>=0).sort((a,b)=>diffDias(a.fecha)-diffDias(b.fecha)),[venc]),cards=useMemo(()=>vencOrd.slice(0,3),[vencOrd]),proximos=useMemo(()=>vencOrd.filter(v=>diffDias(v.fecha)<=10).slice(0,8),[vencOrd]),idx=useMemo(()=>parseInt(catIdx),[catIdx]),os=useMemo(()=>conOS?(categorias[idx]?.os??0):0,[conOS,categorias,idx]),impuesto=catIdx===''?0:actividad==='productos'?(categorias[idx].imp_productos??categorias[idx].imp):categorias[idx].imp,total=useMemo(()=>catIdx===''?0:impuesto+categorias[idx].prev+os,[catIdx,categorias,idx,os,impuesto]),fechaHoy=mounted?new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date()):''
 return <><SiteHeader currentPath="/" onAlertasClick={()=>{capturaRef.current?.scrollIntoView({behavior:'smooth'});setTimeout(()=>capturaRef.current?.focus(),600)}}/><div className="ff-page-content">
 <div className="ff-hero" style={{background:`linear-gradient(135deg,${V.tealDark} 0%,${V.teal} 100%)`,position:'relative',overflow:'hidden'}}><div style={{maxWidth:640,margin:'0 auto',position:'relative',zIndex:1}}><div className="ff-social-proof"><span>🇦🇷</span> Monotributo 2026 · Información actualizada</div><h1>Todo sobre el Monotributo,<br/>explicado fácil</h1><p>Calculá tu categoría, consultá cuánto pagás<br/>y controlá tus próximos vencimientos.</p><div style={{display:'flex',gap:10,justifyContent:'center',flexWrap:'wrap'}}><Link href="/mi-categoria" className="ff-hero-btn">Calcular mi categoría →</Link><Link href="/calendario-fiscal" className="ff-hero-btn" style={{background:'white',color:V.tealDark}}>Ver vencimientos</Link></div><div style={{marginTop:10,fontSize:11,color:'rgba(255,255,255,.5)',fontWeight:600}}>Sin registro · Sin tarjeta · Gratis</div></div></div>
 <section style={{background:V.surface,borderBottom:`1px solid ${V.border}`}}><div style={{maxWidth:860,margin:'0 auto',padding:'18px 16px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><Link href="/mi-categoria" className="ff-card-link">📊 Conocer mi categoría</Link><a href="#cuota-monotributo" className="ff-card-link">💳 Consultar mi cuota</a><a href="#vencimientos-monotributo" className="ff-card-link">📅 Próximos vencimientos</a></div></section>
 <main className="ff-main"><div id="vencimientos-monotributo" style={{scrollMarginTop:90}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20}}><div style={{fontSize:13,color:V.ink3,fontWeight:600}}>Hoy es <strong style={{color:V.ink2}}>{fechaHoy}</strong></div><div style={{background:V.tealLight,border:`1.5px solid ${V.tealRing}`,borderRadius:20,padding:'4px 12px',fontSize:12,fontWeight:800,color:V.tealDark}}>Monotributo</div></div></div>
 <div style={{fontSize:11,fontWeight:800,letterSpacing:'1.5px',textTransform:'uppercase',color:V.ink3,marginBottom:12}}>📅 Próximos vencimientos</div><div className="ff-cards-grid">{cards.length===0?<div style={{padding:'20px 0',color:V.ink3,fontSize:13,fontWeight:600}}>✅ Sin vencimientos próximos inmediatos.</div>:cards.map(v=>{const d=diffDias(v.fecha),c=cardCfg(d);return <div key={v.id} style={{background:c.bg,border:`1.5px solid ${c.border}`,borderRadius:16,padding:18,display:'flex',flexDirection:'column',gap:12}}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{fontSize:20}}>{v.emoji}</div><div style={{background:c.pill.bg,color:c.pill.color,border:`1px solid ${c.pill.border}`,borderRadius:20,padding:'4px 10px',fontSize:11,fontWeight:800}}>{c.txt}</div></div><div><div style={{fontSize:15,fontWeight:900,color:V.ink}}>{v.nombre}</div><div style={{fontSize:12,color:V.ink3}}>{v.detalle}</div></div><div style={{display:'flex',justifyContent:'space-between',borderTop:`1px solid ${V.border}`,paddingTop:10}}><span style={{fontSize:13,fontWeight:700}}>{fmtLarga(v.fecha)}</span><strong style={{fontSize:13,color:c.diasColor}}>{c.diasTxt}</strong></div><a href="/calendario-fiscal" style={{textAlign:'center',padding:10,borderRadius:8,background:V.bg,color:V.ink2,textDecoration:'none',fontSize:13,fontWeight:800}}>Ver detalles →</a></div>})}</div>
 <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden',marginBottom:20}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>📋 Lista de vencimientos del mes</div>{proximos.length===0?<div style={{padding:'14px 16px',color:V.ink3,fontSize:13}}>Sin vencimientos en los próximos 10 días.</div>:proximos.map(v=><div key={v.id} style={{display:'flex',gap:12,padding:'10px 16px',borderBottom:`1px solid ${V.border}`}}><strong style={{fontSize:12,color:V.ink3,minWidth:60}}>{fmtCorta(v.fecha)}</strong><div><div style={{fontSize:13,fontWeight:700,color:V.ink}}>{v.nombre}</div><div style={{fontSize:11,color:V.ink3}}>{v.detalle}</div></div></div>)}</div>
 <div className="ff-two-col"><div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden'}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>⚠️ Alertas importantes</div>{alertas.map(a=><div key={a.id} style={{display:'flex',gap:10,padding:'11px 16px',borderBottom:`1px solid ${V.border}`}}><span>{a.icon}</span><div><div style={{fontSize:12,fontWeight:800,color:V.ink}}>{a.title}</div><div style={{fontSize:11,color:V.ink3,lineHeight:1.5}}>{a.description}</div></div></div>)}</div><div id="cuota-monotributo" style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden'}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>🧮 ¿Cuánto pagás por mes?</div><div style={{padding:'14px 16px'}}><select value={catIdx} onChange={e=>setCatIdx(e.target.value)} style={{width:'100%',padding:9,border:`1.5px solid ${V.border}`,borderRadius:8,marginBottom:8}}><option value="">— Elegí tu categoría —</option>{categorias.map((c,i)=><option key={c.cat} value={i}>Categoría {c.cat}</option>)}</select><select value={actividad} onChange={e=>setActividad(e.target.value as 'servicios'|'productos')} style={{width:'100%',padding:9,border:`1.5px solid ${V.border}`,borderRadius:8,marginBottom:8}}><option value="servicios">Servicios</option><option value="productos">Venta de productos</option></select><label style={{display:'flex',gap:8,fontSize:12,marginBottom:10}}><input type="checkbox" checked={conOS} onChange={e=>setConOS(e.target.checked)}/>Incluir obra social</label><div style={{background:`linear-gradient(135deg,${V.tealDark},${V.tealMid})`,borderRadius:8,padding:16,textAlign:'center',color:'white'}}><div style={{fontSize:28,fontWeight:900}}>{catIdx===''?'—':money(total)}</div><div style={{fontSize:10,opacity:.7}}>cuota mensual estimada</div></div></div></div></div>
 <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden',margin:'20px 0'}}><div style={{background:'#0a0a1a',color:'white',padding:'9px 14px',fontSize:11,fontWeight:700}}>Asistente IA · Consultas fiscales</div><div style={{padding:'12px 14px'}}><div style={{display:'flex',gap:8}}><input value={aiQuery} onChange={e=>setAiQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askAI()} placeholder="¿Qué categoría me corresponde?" style={{flex:1,border:`1.5px solid ${V.border}`,borderRadius:8,padding:'9px 10px',fontSize:13,background:V.bg}}/><button onClick={()=>askAI()} disabled={aiLoading} style={{background:V.teal,color:'white',border:'none',borderRadius:8,padding:'9px 14px',fontWeight:800}}>{aiLoading?'…':'Consultar →'}</button></div>{(aiLoading||aiResp)&&<div style={{marginTop:10,padding:'10px 12px',background:V.bg,borderRadius:8,fontSize:13,color:V.ink2,lineHeight:1.75}}>{aiLoading?'Consultando ARCA…':aiResp}</div>}</div></div>
 <SEOMonotributo/><RegimenQuestions context="monotributo"/><CapturaEmail ref={capturaRef} tipoDefault="mono"/>
 </main></div></>
}
