import Link from 'next/link'
type Context='monotributo'|'autonomos'|'responsable'|'ganancias'
type Question={q:string;a:string;contexts:Context[]}
const questions:Question[]=[
 {q:'¿Qué me conviene: Monotributo o Responsable Inscripto?',a:'Depende de tu caso. El Monotributo suele ser más simple porque pagás una cuota mensual. Como Responsable Inscripto, IVA y Ganancias se calculan por separado y tenés más obligaciones. Para compararlos bien hay que mirar cuánto facturás, tus gastos, tu actividad y a quiénes les vendés.',contexts:['monotributo','responsable']},
 {q:'¿Cuál es la diferencia entre Monotributo y Autónomos?',a:'No son lo mismo. El Monotributo es un régimen simplificado para pequeños contribuyentes e incluye impuestos y aportes en una cuota. Autónomos es principalmente un aporte jubilatorio para determinadas personas que trabajan por cuenta propia fuera del Monotributo.',contexts:['monotributo','autonomos']},
 {q:'¿Responsable Inscripto y Autónomo son lo mismo?',a:'No. Ser Responsable Inscripto se relaciona con tu situación frente al IVA. Autónomos es un régimen de aportes jubilatorios. Por eso una persona puede ser Responsable Inscripto y, al mismo tiempo, pagar Autónomos.',contexts:['responsable','autonomos']},
 {q:'¿Cuándo tengo que pasar de Monotributo a Responsable Inscripto?',a:'Cuando dejás de cumplir alguna condición para seguir en el Monotributo. Puede pasar, por ejemplo, si superás los límites permitidos o aparece otra causa de exclusión. No hay que mirar solamente cuánto facturás.',contexts:['monotributo','responsable']},
 {q:'¿Puedo ser empleado y monotributista al mismo tiempo?',a:'Sí. Podés trabajar en relación de dependencia y además tener una actividad por tu cuenta como monotributista, siempre que cumplas los requisitos del régimen.',contexts:['monotributo']},
 {q:'¿Si soy monotributista también pago Ganancias?',a:'Por la actividad incluida en el Monotributo, Ganancias ya está contemplado dentro de la cuota y no se paga por separado. Pero podés tener otros ingresos que sí estén alcanzados por Ganancias, por ejemplo un sueldo u otras actividades que no formen parte del Monotributo.',contexts:['monotributo','ganancias']},
 {q:'¿A partir de qué sueldo se paga Ganancias?',a:'No hay un único sueldo bruto que sirva para todas las personas. El resultado depende de tus ingresos y de las deducciones que te correspondan, como cargas de familia y otros conceptos admitidos. Por eso conviene calcularlo con tu situación particular.',contexts:['ganancias']},
 {q:'¿Qué pasa si supero el límite de mi categoría?',a:'Primero hay que distinguir si todavía entrás en una categoría más alta del Monotributo. Si superás los límites máximos o dejás de cumplir las condiciones del régimen, podés tener que pasar al régimen general.',contexts:['monotributo']},
 {q:'¿Tengo que pagar Ingresos Brutos además del Monotributo?',a:'Muchas veces sí, porque Ingresos Brutos es un impuesto provincial separado. En algunas jurisdicciones existen regímenes simplificados o unificados. Depende de dónde desarrollás tu actividad y de cómo estés inscripto.',contexts:['monotributo']},
 {q:'¿Cuándo me conviene abrir una sociedad?',a:'No hay un monto de facturación que lo decida por sí solo. Una sociedad puede empezar a tener sentido si vas a tener socios, querés separar mejor el negocio de tu patrimonio personal, necesitás una estructura para crecer o cambia la forma en que trabajás con clientes, proveedores, empleados o inversiones. También hay que comparar sus costos e impuestos.',contexts:['monotributo','responsable','ganancias']},
 {q:'¿Una sociedad paga menos impuestos que una persona?',a:'No necesariamente. Una sociedad tiene sus propios impuestos, gastos y obligaciones. En algunos casos puede ser conveniente y en otros puede resultar más costosa. Por eso no conviene crear una sociedad solamente pensando que siempre va a pagar menos impuestos.',contexts:['responsable','ganancias']},
 {q:'¿Puedo empezar como monotributista y después crear una sociedad?',a:'Sí. Muchos negocios empiezan con una estructura simple y la cambian cuando crecen o aparecen nuevas necesidades. Lo importante es comparar las alternativas antes de hacer el cambio.',contexts:['monotributo']},
]
const titles:Record<Context,string>={monotributo:'Preguntas frecuentes sobre Monotributo',autonomos:'Preguntas frecuentes sobre Autónomos',responsable:'Preguntas frecuentes sobre Responsable Inscripto',ganancias:'Preguntas relacionadas con tu forma de trabajar'}
export default function RegimenQuestions({context='ganancias'}:{context?:Context}){
 const visible=questions.filter(q=>q.contexts.includes(context))
 return <section style={{background:'#fff',border:'1.5px solid #e2e8ed',borderRadius:14,overflow:'hidden',margin:'20px 0',boxShadow:'0 1px 4px rgba(13,92,120,.07)'}}>
  <div style={{padding:'15px 16px',borderBottom:'1px solid #e2e8ed'}}><h2 style={{fontSize:18,margin:0,color:'#0f2733'}}>{titles[context]}</h2><p style={{fontSize:12,color:'#3d5a6b',margin:'5px 0 0',lineHeight:1.6}}>Respuestas cortas y simples a dudas comunes. Abrí cada pregunta para ver la explicación.</p></div>
  {visible.map((item,i)=><details key={item.q} style={{padding:'13px 16px',borderBottom:i===visible.length-1?'none':'1px solid #e2e8ed'}}><summary style={{cursor:'pointer',fontSize:13,fontWeight:800,color:'#0f2733'}}>{item.q}</summary><p style={{fontSize:12,color:'#3d5a6b',fontWeight:600,lineHeight:1.75,margin:'9px 0 0'}}>{item.a}</p></details>)}
  <div style={{padding:16,background:'#e8f6fb',borderTop:'1px solid #a8ddf0'}}><strong style={{display:'block',fontSize:14,color:'#0d5c78'}}>¿No sabés qué opción te conviene?</strong><p style={{fontSize:12,color:'#3d5a6b',lineHeight:1.6,margin:'5px 0 12px'}}>Compará las alternativas usando los datos de tu negocio.</p><Link href="/crear-negocio" style={{display:'inline-block',background:'#0d5c78',color:'#fff',padding:'10px 14px',borderRadius:9,fontSize:13,fontWeight:800,textDecoration:'none'}}>Evaluar mi negocio →</Link></div>
 </section>
}