'use client'
import { useState } from 'react'
import SiteHeader from '@/components/SiteHeader'
import { SEOComoFacturar } from '@/components/SEOContent/SEOContent'
import { RelatedGuide } from '@/components/SEOContent/CalculatorSEOBlocks'

const V={tealDark:'#0d5c78',teal:'#1a7fa8',tealLight:'#e8f6fb',tealRing:'#a8ddf0',goldLight:'#fff8ec',goldRing:'#fde4a0',bg:'#f4f7f9',surface:'#fff',border:'#e2e8ed',ink:'#0f2733',ink2:'#3d5a6b',ink3:'#7a9aaa'}

export default function ComoFacturar(){
 const[aiQuery,setAiQuery]=useState(''),[aiResp,setAiResp]=useState(''),[aiLoad,setAiLoad]=useState(false)
 async function askAI(q?:string){const query=q||aiQuery;if(!query.trim())return;if(q)setAiQuery(q);setAiLoad(true);setAiResp('');try{const r=await fetch('/api/fiscal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const d=await r.json();setAiResp(d.response||'Sin respuesta.')}catch{setAiResp('Error de conexión.')}finally{setAiLoad(false)}}
 const pasos=[
  ['1','Entrá a ARCA','Ingresá al sitio oficial con tu CUIT y clave fiscal. Para Comprobantes en línea necesitás el nivel de seguridad requerido por ARCA.'],
  ['2','Dá de alta el punto de venta','Antes de facturar, configurá un punto de venta asociado al sistema que vas a utilizar. Cada modalidad necesita su punto de venta correspondiente.'],
  ['3','Elegí cómo vas a facturar','Podés usar Comprobantes en línea y, si sos monotributista y cumplís sus requisitos, también el Facturador. ARCA contempla además otras modalidades habilitadas.'],
  ['4','Elegí el comprobante correcto','Un monotributista emite C, salvo exportaciones donde corresponde E. Un Responsable Inscripto emite A a RI o monotributistas y B a consumidores finales o exentos.'],
  ['5','Cargá la operación real','Indicá concepto, fecha, datos del receptor cuando correspondan, descripción, cantidad e importe. No inventes datos para completar campos.'],
  ['6','Revisá antes de confirmar','Controlá tipo de comprobante, punto de venta, receptor, moneda, fecha e importe antes de solicitar la autorización.'],
  ['7','Conservá el comprobante autorizado','Guardá el comprobante y su autorización. Si después necesitás corregirlo, utilizá la nota de crédito o débito que corresponda vinculada al comprobante original.'],
 ]
 return <><SiteHeader currentPath="/como-facturar"/><div className="ff-page-content"><main style={{maxWidth:860,margin:'0 auto',padding:'32px 24px 80px'}}>
  <div style={{background:`linear-gradient(135deg,${V.tealDark},${V.teal})`,borderRadius:16,padding:'28px 32px',marginBottom:28,color:'white'}}><div style={{fontSize:11,fontWeight:800,letterSpacing:'2px',textTransform:'uppercase',opacity:.65,marginBottom:6}}>Guía paso a paso</div><h1 style={{fontSize:26,fontWeight:900,margin:'0 0 6px'}}>Cómo emitir una factura electrónica</h1><div style={{fontSize:13,opacity:.75}}>Monotributo y régimen general · ARCA · Revisado septiembre 2026</div></div>
  <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:16,overflow:'hidden',marginBottom:24}}><div style={{padding:'14px 18px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800,color:V.ink}}>📋 Pasos para emitir un comprobante</div>{pasos.map(([n,t,d],i)=><div key={n} style={{display:'flex',gap:16,padding:'16px 18px',borderBottom:i<pasos.length-1?`1px solid ${V.border}`:'none'}}><div style={{width:32,height:32,borderRadius:'50%',background:V.tealLight,border:`2px solid ${V.teal}`,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,fontSize:14,fontWeight:900,color:V.teal}}>{n}</div><div><div style={{fontSize:14,fontWeight:800,color:V.ink,marginBottom:4}}>{t}</div><div style={{fontSize:13,color:V.ink2,lineHeight:1.6}}>{d}</div></div></div>)}</div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14,marginBottom:24}}><div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:12,padding:'16px 18px'}}><div style={{fontSize:13,fontWeight:800,color:V.ink,marginBottom:10}}>Si sos monotributista</div><div style={{fontSize:12,color:V.ink2,lineHeight:1.65}}>Emitís comprobante <strong>C</strong> para tus operaciones habituales, cualquiera sea la condición de tu cliente. Para exportaciones corresponde comprobante <strong>E</strong>.</div></div><div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:12,padding:'16px 18px'}}><div style={{fontSize:13,fontWeight:800,color:V.ink,marginBottom:10}}>Si sos Responsable Inscripto</div><div style={{fontSize:12,color:V.ink2,lineHeight:1.65}}>En general emitís <strong>A</strong> a otros RI y a monotributistas, <strong>B</strong> a consumidores finales o exentos y <strong>E</strong> en exportaciones.</div></div></div>
  <div style={{background:V.goldLight,border:`1px solid ${V.goldRing}`,borderRadius:12,padding:'15px 17px',marginBottom:24,fontSize:13,color:'#7a4f00',lineHeight:1.65}}><strong>Importante:</strong> no existe una única regla de fecha para todos los comprobantes. ARCA diferencia ventas de cosas muebles, servicios, servicios continuos, locaciones y anticipos. Más abajo tenés el detalle actualizado.</div>
  <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:12,padding:'16px 18px',marginBottom:24}}><div style={{fontSize:13,fontWeight:800,color:V.ink,marginBottom:12}}>🔗 Fuentes oficiales</div><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{[
   ['Facturación para monotributistas','https://www.arca.gob.ar/monotributo/ayuda/facturacion.asp'],
   ['Comprobantes de régimen general','https://www.arca.gob.ar/facturacion/regimen-general/comprobantes.asp'],
   ['Cuándo emitir un comprobante','https://www.arca.gob.ar/facturacion/comprobantes/emision.asp'],
   ['Factura electrónica','https://www.arca.gob.ar/fe/'],
   ['Facturador','https://www.arca.gob.ar/facturador/'],
  ].map(([label,href])=><a key={label} href={href} target="_blank" rel="noopener noreferrer" style={{background:V.tealLight,border:`1px solid ${V.tealRing}`,borderRadius:6,padding:'6px 12px',fontSize:12,fontWeight:700,color:V.tealDark,textDecoration:'none'}}>{label} →</a>)}</div></div>
  <div style={{marginBottom:24,background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:16,overflow:'hidden'}}><div style={{background:'#0a0a1a',color:'white',padding:'10px 16px',fontSize:11,fontWeight:700}}>Asistente Fiscal IA · Dudas sobre facturación</div><div style={{padding:'14px 16px'}}><div style={{display:'flex',gap:8}}><input value={aiQuery} onChange={e=>setAiQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askAI()} placeholder="Ej.: ¿Qué factura corresponde a mi cliente?" style={{flex:1,border:`1.5px solid ${V.border}`,borderRadius:8,padding:'10px 12px',fontSize:13,background:V.bg}}/><button onClick={()=>askAI()} disabled={aiLoad} style={{background:V.teal,color:'white',border:'none',borderRadius:8,padding:'10px 18px',fontSize:13,fontWeight:800}}>{aiLoad?'…':'Consultar →'}</button></div>{(aiLoad||aiResp)&&<div style={{marginTop:12,padding:'12px 14px',background:V.bg,borderRadius:8,borderLeft:`3px solid ${V.teal}`,fontSize:13,color:V.ink2,lineHeight:1.75,whiteSpace:'pre-wrap'}}>{aiLoad?'Consultando ARCA…':aiResp}</div>}</div></div>
  <SEOComoFacturar/><RelatedGuide href="/factura-c" title="Factura C: qué es y cuándo corresponde" text="Conocé quién la emite, qué datos lleva y en qué casos se usa un comprobante diferente."/>
 </main></div></>
}
