'use client'
import { useEffect,useMemo,useRef,useState } from 'react'
import SiteHeader from '@/components/SiteHeader'
import CapturaEmail from '@/components/CapturaEmail'
import { SEOResponsableInscripto } from '@/components/SEOContent/SEOContent'
import { RelatedGuide } from '@/components/SEOContent/CalculatorSEOBlocks'
import { FALLBACK_VENC,FALLBACK_ALERTAS,addFecha,diffDias,fmtLarga,fmtCorta,type VencimientoUI,type AlertaUI } from '@/lib/data'

const TIPO='ri'
const V={tealDark:'#0d5c78',teal:'#1a7fa8',tealLight:'#e8f6fb',tealRing:'#a8ddf0',goldLight:'#fff8ec',goldRing:'#fde4a0',red:'#e53535',redBg:'#fff1f1',redRing:'#ffc8c8',amber:'#d97706',amberBg:'#fffbeb',amberRing:'#fde68a',bg:'#f4f7f9',surface:'#fff',border:'#e2e8ed',ink:'#0f2733',ink2:'#3d5a6b',ink3:'#7a9aaa'}
function cfg(d:number){return d===0?{bg:V.redBg,border:V.redRing,color:V.red,label:'Vence HOY'}:d===1?{bg:V.goldLight,border:V.goldRing,color:V.amber,label:'Mañana'}:{bg:V.tealLight,border:V.tealRing,color:V.tealDark,label:`En ${d} días`}}

export default function ResponsableInscriptoPage(){
 const[venc,setVenc]=useState<VencimientoUI[]>([]),[alertas,setAlertas]=useState<AlertaUI[]>([]),[aiQuery,setAiQuery]=useState(''),[aiResp,setAiResp]=useState(''),[aiLoading,setAiLoading]=useState(false),[mounted,setMounted]=useState(false)
 const capturaRef=useRef<HTMLInputElement>(null)
 useEffect(()=>setMounted(true),[])
 useEffect(()=>{fetch(`/api/vencimientos?tipo=${TIPO}`).then(r=>r.json()).then(d=>setVenc((d.vencimientos||[]).map(addFecha))).catch(()=>setVenc(FALLBACK_VENC[TIPO].map(addFecha)));fetch(`/api/alerts?tipo=${TIPO}`).then(r=>r.json()).then(d=>setAlertas(d.alerts||FALLBACK_ALERTAS[TIPO])).catch(()=>setAlertas(FALLBACK_ALERTAS[TIPO]))},[])
 async function askAI(q?:string){const query=q||aiQuery;if(!query.trim())return;if(q)setAiQuery(q);setAiLoading(true);setAiResp('');try{const r=await fetch('/api/fiscal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const d=await r.json();setAiResp(d.response||'Sin respuesta.')}catch{setAiResp('Error de conexión.')}finally{setAiLoading(false)}}
 const vencOrd=useMemo(()=>[...venc].filter(v=>diffDias(v.fecha)>=0).sort((a,b)=>diffDias(a.fecha)-diffDias(b.fecha)),[venc]),cards=vencOrd.slice(0,3),proximos=vencOrd.filter(v=>diffDias(v.fecha)<=10).slice(0,8)
 const fechaHoy=mounted?new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date()):''
 return <><SiteHeader currentPath="/responsable-inscripto" onAlertasClick={()=>{capturaRef.current?.scrollIntoView({behavior:'smooth'});setTimeout(()=>capturaRef.current?.focus(),600)}}/><div className="ff-page-content">
  <div className="ff-hero" style={{background:`linear-gradient(135deg,${V.tealDark},${V.teal})`}}><div style={{maxWidth:650,margin:'0 auto'}}><div style={{display:'inline-flex',background:'rgba(255,255,255,.12)',border:'1px solid rgba(255,255,255,.2)',borderRadius:20,padding:'5px 14px',marginBottom:16,fontSize:12,fontWeight:700,color:'white'}}>🏢 Para Responsables Inscriptos</div><h1>IVA, Ganancias y vencimientos<br/>explicados de forma simple</h1><p>Revisá tus obligaciones, calculá estimaciones con las herramientas específicas y activá recordatorios.</p><a href="https://www.arca.gob.ar/regimenGeneral/" target="_blank" rel="noopener noreferrer" className="ff-hero-btn">Ver Régimen General en ARCA →</a></div></div>
  <div style={{background:V.surface,borderBottom:`1px solid ${V.border}`}}><div style={{maxWidth:860,margin:'0 auto',padding:'20px 16px'}}><div style={{textAlign:'center',marginBottom:14}}><div style={{fontSize:13,fontWeight:800,color:V.red}}>⚠️ Evitá errores ante ARCA</div><div style={{fontSize:16,fontWeight:900,color:V.ink}}>Puntos que conviene revisar</div></div><div className="ff-dolor-grid">{['Presentar IVA fuera de término','No computar correctamente retenciones o percepciones','Emitir un comprobante distinto al autorizado','Pagar anticipos sin revisar el cálculo vigente'].map(txt=><div key={txt} style={{display:'flex',gap:8,background:V.redBg,border:`1px solid ${V.redRing}`,borderRadius:10,padding:'10px 12px'}}><span>❌</span><span style={{fontSize:12,fontWeight:700,color:'#7a2020',lineHeight:1.4}}>{txt}</span></div>)}</div></div></div>
  <main className="ff-main"><div style={{display:'flex',justifyContent:'space-between',marginBottom:20}}><div style={{fontSize:13,color:V.ink3}}>Hoy es <strong style={{color:V.ink2}}>{fechaHoy}</strong></div><div style={{background:V.tealLight,border:`1px solid ${V.tealRing}`,borderRadius:20,padding:'4px 10px',fontSize:12,fontWeight:800,color:V.tealDark}}>🧾 Responsable Inscripto</div></div>
   <div style={{fontSize:11,fontWeight:800,letterSpacing:'1.5px',textTransform:'uppercase',color:V.ink3,marginBottom:12}}>📅 Próximos vencimientos</div><div className="ff-cards-grid">{cards.length===0?<div style={{padding:'20px 0',color:V.ink3,fontSize:13}}>No hay una fecha exacta próxima disponible para mostrar acá. Consultá el calendario fiscal.</div>:cards.map(v=>{const d=diffDias(v.fecha),c=cfg(d);return <div key={v.id} style={{background:'#fff',border:`1.5px solid ${c.border}`,borderRadius:16,padding:18,display:'flex',flexDirection:'column',gap:12}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:20}}>🧾</span><span style={{background:c.bg,color:c.color,borderRadius:20,padding:'4px 10px',fontSize:11,fontWeight:800}}>{c.label}</span></div><div><div style={{fontSize:15,fontWeight:900,color:V.ink}}>{v.nombre}</div><div style={{fontSize:12,color:V.ink3,marginTop:3}}>{v.detalle}</div></div><div style={{display:'flex',justifyContent:'space-between',borderTop:`1px solid ${V.border}`,paddingTop:10}}><span style={{fontSize:13,fontWeight:700}}>{fmtLarga(v.fecha)}</span><strong style={{fontSize:13,color:c.color}}>{c.label}</strong></div><a href="/calendario-fiscal" style={{textAlign:'center',padding:10,borderRadius:8,background:V.bg,color:V.ink2,textDecoration:'none',fontSize:13,fontWeight:800}}>Ver calendario →</a></div>})}</div>
   <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden',marginBottom:20}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>📋 Vencimientos próximos</div>{proximos.length===0?<div style={{padding:'14px 16px',color:V.ink3,fontSize:13}}>Sin fechas exactas en los próximos 10 días.</div>:proximos.map(v=><div key={v.id} style={{display:'flex',gap:12,padding:'10px 16px',borderBottom:`1px solid ${V.border}`}}><strong style={{fontSize:12,color:V.ink3,minWidth:60}}>{fmtCorta(v.fecha)}</strong><div><div style={{fontSize:13,fontWeight:700,color:V.ink}}>{v.nombre}</div><div style={{fontSize:11,color:V.ink3}}>{v.detalle}</div></div></div>)}</div>
   <div className="ff-two-col"><div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden'}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>⚠️ Alertas importantes</div>{alertas.map(a=><div key={a.id} style={{display:'flex',gap:10,padding:'11px 16px',borderBottom:`1px solid ${V.border}`}}><span>{a.icon}</span><div><div style={{fontSize:12,fontWeight:800,color:V.ink}}>{a.title}</div><div style={{fontSize:11,color:V.ink3,lineHeight:1.5}}>{a.description}</div></div></div>)}</div>
    <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden'}}><div style={{padding:'13px 16px',borderBottom:`1px solid ${V.border}`,fontSize:14,fontWeight:800}}>🧮 Calculá cada obligación por separado</div><div style={{padding:'14px 16px',display:'grid',gap:10}}><a href="/iva" style={{background:V.tealLight,border:`1px solid ${V.tealRing}`,borderRadius:9,padding:'11px 12px',textDecoration:'none',color:V.tealDark,fontWeight:800}}>IVA — estimar saldo del período →</a><a href="/impuesto-ganancias" style={{background:V.goldLight,border:`1px solid ${V.goldRing}`,borderRadius:9,padding:'11px 12px',textDecoration:'none',color:'#7a4f00',fontWeight:800}}>Ganancias — estimación anual →</a><a href="/autonomos" style={{background:V.bg,border:`1px solid ${V.border}`,borderRadius:9,padding:'11px 12px',textDecoration:'none',color:V.ink2,fontWeight:800}}>Autónomos — si sos persona humana alcanzada →</a><p style={{fontSize:11,color:V.ink3,lineHeight:1.5,margin:0}}>No existe una “cuota mensual de Responsable Inscripto” que reúna IVA, Ganancias y aportes. Cada obligación se determina por separado.</p></div></div></div>
   <div style={{background:V.surface,border:`1.5px solid ${V.border}`,borderRadius:14,overflow:'hidden',margin:'20px 0'}}><div style={{background:'#0a0a1a',color:'white',padding:'9px 14px',fontSize:11,fontWeight:700}}>Asistente IA · Consultas fiscales</div><div style={{padding:'12px 14px'}}><div style={{display:'flex',gap:8}}><input value={aiQuery} onChange={e=>setAiQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askAI()} placeholder="¿Cuándo vence mi IVA?" style={{flex:1,border:`1.5px solid ${V.border}`,borderRadius:8,padding:'9px 10px',fontSize:13,background:V.bg}}/><button onClick={()=>askAI()} disabled={aiLoading} style={{background:V.teal,color:'white',border:'none',borderRadius:8,padding:'9px 14px',fontWeight:800}}>{aiLoading?'…':'Consultar →'}</button></div>{(aiLoading||aiResp)&&<div style={{marginTop:10,padding:'10px 12px',background:V.bg,borderRadius:8,borderLeft:`3px solid ${V.teal}`,fontSize:13,color:V.ink2,lineHeight:1.75,whiteSpace:'pre-wrap'}}>{aiLoading?'Consultando ARCA…':aiResp}</div>}</div></div>
   <SEOResponsableInscripto/><RelatedGuide href="/responsable-inscripto-obligaciones" title="Checklist de obligaciones del Responsable Inscripto" text="Revisá IVA, Ganancias, facturación, impuestos provinciales y obligaciones que dependen de tu actividad."/><CapturaEmail ref={capturaRef} tipoDefault="ri"/>
  </main></div></>
}
