'use client'
import { useState } from 'react'
import type { CSSProperties,ReactNode } from 'react'
import { calcularIVA,estimarGananciasSimple,VERIFICACION_FISCAL } from '@/lib/calculadoras-fiscales'

const money=(n:number)=>n.toLocaleString('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0})
const n=(v:string)=>Number(v)||0
const input:CSSProperties={width:'100%',minHeight:48,padding:'11px 13px',border:'2px solid #e2e8f0',borderRadius:9,fontFamily:'inherit',fontSize:16,lineHeight:1.4,boxSizing:'border-box',marginTop:7}
const grid:CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:16}
const formSection:CSSProperties={marginTop:26}
const question:CSSProperties={margin:'0 0 10px',fontSize:'clamp(18px,2vw,20px)',lineHeight:1.4,fontWeight:600,color:'#183744'}
const fieldLabel:CSSProperties={display:'block',fontSize:15,lineHeight:1.45,color:'#243b4a'}
function Shell({title,intro,color,source,children}:{title:string;intro:string;color:string;source:string;children:ReactNode}){return <main style={{background:'#f8fafc',minHeight:'100vh',fontFamily:'Nunito, sans-serif',color:'#102a36'}}><header style={{background:color,color:'white',padding:'clamp(36px,6vw,52px) 20px',textAlign:'center'}}><h1 style={{fontSize:'clamp(30px,5vw,46px)',lineHeight:1.15,margin:'0 0 12px',fontWeight:900}}>{title}</h1><p style={{maxWidth:700,margin:'0 auto',fontSize:'clamp(16px,2vw,18px)',lineHeight:1.5}}>{intro}</p></header><section style={{maxWidth:820,margin:'0 auto',padding:'clamp(24px,4vw,36px) 18px 40px'}}><div style={{background:'white',padding:'clamp(22px,4vw,34px)',borderRadius:16,boxShadow:'0 4px 24px #0f172a14'}}>{children}</div><p style={{margin:'12px 0 0',fontSize:13,color:'#64748b',lineHeight:1.6}}>Revisado el {VERIFICACION_FISCAL}. <a href={source} target="_blank" rel="noopener noreferrer">Ver fuente oficial</a>. Es una estimación orientativa: el importe definitivo depende de tu situación y de lo informado ante ARCA.</p></section></main>}
function Choice({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" onClick={onClick} style={{minHeight:50,padding:'11px 13px',borderRadius:9,border:`2px solid ${active?'#0d9488':'#e2e8f0'}`,background:active?'#ecfdf5':'white',fontFamily:'inherit',fontSize:15,fontWeight:600,cursor:'pointer'}}>{children}</button>}
function Result({label,value,main=false}:{label:string;value:string;main?:boolean}){return <div style={{background:main?'#ecfdf5':'#f1f5f9',border:main?'2px solid #86efac':'none',padding:18,borderRadius:10}}><div style={{fontSize:13,color:'#475569'}}>{label}</div><strong style={{fontSize:main?27:21,color:main?'#166534':'#0f172a'}}>{value}</strong></div>}
function More({open,setOpen,children}:{open:boolean;setOpen:(v:boolean)=>void;children:ReactNode}){return <><button type="button" onClick={()=>setOpen(!open)} style={{display:'block',marginTop:22,padding:'4px 0',border:'none',background:'none',color:'#0d5c78',fontFamily:'inherit',fontSize:14,fontWeight:800,cursor:'pointer'}}>⚙️ {open?'Ocultar opciones adicionales':'Tengo más datos para mejorar el cálculo'}</button>{open?<div style={{marginTop:14,padding:18,background:'#f8fafc',borderRadius:12}}>{children}</div>:null}</>}

export function GananciasCalculator(){
 const[tipo,setTipo]=useState<'empleado'|'independiente'>('empleado'),[ing,setIng]=useState(''),[meses,setMeses]=useState('13'),[gastos,setGastos]=useState(''),[hijos,setHijos]=useState('0'),[conyuge,setConyuge]=useState(false),[alquiler,setAlquiler]=useState(''),[prepaga,setPrepaga]=useState(''),[domestico,setDomestico]=useState(''),[more,setMore]=useState(false)
 const r=estimarGananciasSimple({tipo,ingresoMensual:n(ing),meses:n(meses),gastosMensuales:n(gastos),hijos:n(hijos),conyuge,alquilerMensual:n(alquiler),prepagaMensual:n(prepaga),personalDomesticoMensual:n(domestico)})
 return <Shell title="Calculadora de Ganancias 2026" intro="Estimá el impuesto anual con la escala y deducciones personales publicadas por ARCA." color="linear-gradient(135deg,#7c3aed,#4c1d95)" source="https://www.arca.gob.ar/gananciasYBienes/ganancias/personas-humanas-sucesiones-indivisas/declaracion-jurada/determinativa/determinacion.asp">
  <section><h2 style={question}>1. ¿Cómo trabajás?</h2><div style={grid}><Choice active={tipo==='empleado'} onClick={()=>{setTipo('empleado');setMeses('13')}}>👔 Relación de dependencia</Choice><Choice active={tipo==='independiente'} onClick={()=>{setTipo('independiente');setMeses('12')}}>💼 Trabajo por mi cuenta</Choice></div></section>
  <section style={formSection}><h2 style={question}>2. ¿Cuánto cobrás normalmente?</h2><label style={fieldLabel}>{tipo==='empleado'?'Sueldo bruto mensual':'Ingresos o facturación mensual'}<input style={input} type="number" min="0" value={ing} onChange={e=>setIng(e.target.value)} placeholder="Ej.: 2500000"/></label>{tipo==='independiente'?<label style={{display:'block',marginTop:14}}>Gastos mensuales vinculados con la actividad<input style={input} type="number" min="0" value={gastos} onChange={e=>setGastos(e.target.value)}/></label>:null}</section>
  <section style={formSection}><h2 style={question}>3. Tu situación familiar</h2><div style={grid}><label style={fieldLabel}>Hijos menores o a cargo<select style={input} value={hijos} onChange={e=>setHijos(e.target.value)}>{[0,1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label style={{display:'flex',gap:10,alignItems:'center',paddingTop:27}}><input type="checkbox" checked={conyuge} onChange={e=>setConyuge(e.target.checked)}/> Cónyuge a cargo que cumple los requisitos de la deducción</label></div></section>
  <More open={more} setOpen={setMore}><div style={grid}><label>Alquiler mensual de vivienda<input style={input} type="number" value={alquiler} onChange={e=>setAlquiler(e.target.value)}/></label><label>Cuota médico-asistencial computable<input style={input} type="number" value={prepaga} onChange={e=>setPrepaga(e.target.value)}/></label><label>Personal de casas particulares computable<input style={input} type="number" value={domestico} onChange={e=>setDomestico(e.target.value)}/></label><label>Pagos considerados<select style={input} value={meses} onChange={e=>setMeses(e.target.value)}><option value="12">12 meses</option><option value="13">12 meses + SAC aproximado</option></select></label></div></More>
  <div style={{...grid,marginTop:26}}><Result main label="Ganancias anual estimada" value={money(r.impuesto)}/><Result label="Promedio mensual orientativo" value={money(r.impuesto/12)}/><Result label="Ingreso anual considerado" value={money(r.ingresoAnual)}/></div>
  <p style={{background:'#fff7ed',padding:14,borderRadius:10,lineHeight:1.55}}>Esta herramienta simplifica situaciones complejas. En empleados estima aportes personales y no reemplaza la liquidación del empleador ni SiRADIG. En independientes, la deducibilidad de cada gasto depende de los requisitos legales y de su vinculación con la actividad.</p>
 </Shell>
}

export function IVACalculator(){
 const[ventas,setVentas]=useState(''),[compras,setCompras]=useState(''),[incluye,setIncluye]=useState(true),[tasa,setTasa]=useState('.21'),[ret,setRet]=useState(''),[more,setMore]=useState(false)
 const rate=Number(tasa),net=(x:number)=>incluye?x/(1+rate):x,r=calcularIVA({ventas:[{neto:net(n(ventas)),tasa:rate}],compras:[{neto:net(n(compras)),tasa:rate}],retenciones:n(ret)})
 return <Shell title="Calculadora de IVA 2026" intro="Estimá débito y crédito fiscal cuando tus operaciones principales usan una misma alícuota." color="linear-gradient(135deg,#0891b2,#155e75)" source="https://www.arca.gob.ar/iva/responsables-inscriptos/">
  <section><h2 style={question}>¿Cuánto vendiste este mes?</h2><input style={input} type="number" value={ventas} onChange={e=>setVentas(e.target.value)} placeholder="Total de ventas con esta alícuota"/></section>
  <section style={formSection}><h2 style={question}>¿Cuánto compraste con crédito fiscal computable?</h2><input style={input} type="number" value={compras} onChange={e=>setCompras(e.target.value)} placeholder="Compras y gastos alcanzados por la misma tasa"/></section>
  <div style={{...grid,marginTop:24}}><label style={fieldLabel}>¿Los importes incluyen IVA?<select style={input} value={incluye?'si':'no'} onChange={e=>setIncluye(e.target.value==='si')}><option value="si">Sí, son totales de factura</option><option value="no">No, son importes netos</option></select></label><label style={fieldLabel}>Alícuota a usar<select style={input} value={tasa} onChange={e=>setTasa(e.target.value)}><option value=".21">21%</option><option value=".105">10,5%</option><option value=".27">27%</option></select></label></div>
  <More open={more} setOpen={setMore}><label>Retenciones y percepciones computables del período<input style={input} type="number" value={ret} onChange={e=>setRet(e.target.value)}/></label></More>
  <div style={{...grid,marginTop:26}}><Result label="IVA de ventas" value={money(r.debito)}/><Result label="IVA de compras" value={money(r.credito)}/><Result main label={r.pagar?'Saldo estimado a pagar':'Saldo estimado a favor'} value={money(r.pagar||r.saldoFavor)}/></div>
  <p style={{background:'#fff7ed',padding:14,borderRadius:10,lineHeight:1.55}}>Si tenés operaciones a distintas alícuotas, exentas, no gravadas, saldos anteriores u otros pagos a cuenta, este cálculo simple no alcanza. La declaración mensual se presenta mediante IVA Simple para los períodos alcanzados.</p>
 </Shell>
}
